print('Hello world')
print('What is your name?')
myName = input()
print('Its nice to meet You, ' + myName)
print('The length of Your name is: ' + str(len(myName)))
print('How old are You? ')
print('What is Your age?')
age = input()
print('You will be ' + str(int(age)+1) + ' next year')